# Generated by Django 4.2.8 on 2024-12-28 12:15

from django.db import migrations, models
import django.db.models.deletion
import xfb_pay_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='客服姓名')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='客服手机号')),
                ('password', models.CharField(max_length=128, verbose_name='客服密码')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='会话密钥')),
            ],
            options={
                'verbose_name': '客服',
                'verbose_name_plural': '客服管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品定价')),
                ('user_day', models.IntegerField(default=0, verbose_name='用户使用天数')),
                ('cover_image', models.ImageField(help_text='支持jpg、png、gif格式，大小不超过5MB', upload_to='products/covers', validators=[xfb_pay_app.models.validate_image], verbose_name='封面图片')),
                ('detail_image', models.ImageField(help_text='支持jpg、png、gif格式，大小不超过5MB', upload_to='products/details', validators=[xfb_pay_app.models.validate_image], verbose_name='详情图片')),
                ('url_code', models.CharField(blank=True, max_length=100, unique=True, verbose_name='商品编码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('purchase_count', models.IntegerField(default=0, verbose_name='购买次数')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='商品备注信息')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='商品名称')),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='商品价格')),
                ('customer_service', models.CharField(blank=True, max_length=255, null=True, verbose_name='归属客服')),
                ('buyer_nickname', models.CharField(default='未知', max_length=20, verbose_name='买家微信昵称')),
                ('buyer_name', models.CharField(max_length=8, verbose_name='买家姓名')),
                ('buyer_phone', models.CharField(max_length=11, verbose_name='买家联系电话')),
                ('buyer_company', models.CharField(max_length=50, verbose_name='买家单位')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('payment_status', models.CharField(choices=[('paid', '已支付'), ('pending', '待支付'), ('canceled', '已取消')], default='pending', max_length=20, verbose_name='支付状态')),
                ('notes', models.TextField(blank=True, max_length=3000, null=True, verbose_name='备注')),
                ('order_number', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='订单号')),
                ('payment_link', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='支付链接')),
                ('payment_link_expires', models.DateTimeField(blank=True, null=True, verbose_name='支付链接过期时间')),
                ('payment_link_used', models.BooleanField(default=False, verbose_name='支付链接是否已用')),
                ('payment_code', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='支付码')),
                ('product_user_day', models.IntegerField(blank=True, default=0, null=True, verbose_name='商品使用天数')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xfb_pay_app.product', verbose_name='��品')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
