# Generated by Django 4.2.8 on 2024-12-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xfb_pay_app', '0002_alter_order_product_alter_product_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_name',
            field=models.CharField(blank=True, help_text='订单创建时的商品名称，不随原商品变化', max_length=200, null=True, verbose_name='订单商品名称'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_company',
            field=models.CharField(max_length=50, verbose_name='买家工作单位'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='订单金额'),
        ),
    ]
